/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by `next dev` / `next build`.
// It's checked in here only so the project type-checks before the
// first build; Next.js will overwrite it automatically.
